#Hey thanks for buying my Lobby Core I hope you like it 
#Hey gracias por comprar mi Lobby Core espero que te guste
Motd: "§l§aBest Server"
#change the motd of the server
#cambia el motd del server
Discord: "§l§bHey aqui esta Nuestro discord: Discord.gg/bestserver"
#here you can put your discord link 
#aqui puedes poner tu link de discord
