#Hey thanks for buying my Lobby Core I hope you like it 
#Hey gracias por comprar mi Lobby Core espero que te guste
Motd: "§l§aBest Server"
#change the motd of the server
#cambia el motd del server
ServerName: "Best Server"
#here you put the name of your server 
#aqui pones el nombre de tu server
ServerShop: "BestServer.tebex.ui"
#here you put the name of your store or page of your server 
#aqui pones el nombre o la pagina de tu tienda de tu server