#Hey thanks for buying my Lobby Core I hope you like it 
#Hey gracias por comprar mi Lobby Core espero que te guste
Motd: "§l§aBest Server"
#change the motd of the server
#cambia el motd del server
TiTle: "§l§dScoreboard Name"
#this is the title of your scoreboard 
#este es el titulo de tu scoreboard
Line-1: "---------------------"
Line-2: "---------------------"
#lines that appear on the scoreboard 
#lineas que aparecen en el scoreboard